apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:jF2547m5i/+8ZP9JzrYXNBogWs6q+AMIvOBG7uibbTM9rIS/fZo0iLLETjkuni5y,iv:9qclUWL4i5twXzsgZpIROS7Q1gVIQ0sP3K9KeDBFfDw=,tag:4x/zb69U9DCDVP7+3If/mA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ24zdVEwdUlrN1hYVG1s
            M3YxaU9ZeVVFeVI5NW1wd0NkcFNDSTdjNG1ZCkNpUnVxYVdENmdkM3dueDljcCtU
            ZWh3OFRoVkdvck5MR3h2Ump4cVltQXcKLS0tIHMzZW1GSWd4K3lLVmd3bzRYQW5k
            ZHJhc1lWUXc3K3dJNE5OYmU0N0pyMVkKDy2mEeJaduy6IqKIFJ0nSOU0SZIf6eFr
            VNxbsQ8kOvlYVNLm/m6ImG0YjTUs0E4bB51r361KLfTCGS5KrcWDZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T10:51:35Z"
    mac: ENC[AES256_GCM,data:5sSsUECEZzXNVUw5VvEu20aOrGuRZnlDZ9a3NKCbHBE2EeqmCIxFYQY9yk1u5bu7HxSxusxJQ0BNFvATIhbvhMo901lfQ5KK5pnUZbd8jWj8c3Dxo/jH5zJ554mxtOOBpqSWlCVvRwzWsXjhXev+mNMfjkzrXmQNfs2x0XUiCwI=,iv:pDM96/Lnd8O2KIl2QA4AhTpPFEm2rm7qny35UQupWJA=,tag:p6DvP1moC4z3+ZYa6CZi3Q==,type:str]
    version: 3.13.1
