creation_rules:
  - path_regex: kubernetes/apps/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
  - path_regex: kubernetes/apps/.*\.enc\.ya?ml
    age: >-
      age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
  - path_regex: kubernetes/init/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4
  - path_regex: network/adguardhome\.sops\.ya?ml
    encrypted_regex: "^(password)$"
    age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4
  - age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4
