creation_rules:
  - path_regex: kubernetes/apps/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    pgp: "65FFACBA29AFAFECC3F614C8F03D887806414471"
  - path_regex: kubernetes/init/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4
  - path_regex: network/adguardhome\.sops\.ya?ml
    encrypted_regex: "^(password)$"
    age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4
  - age: >-
      age1jfervsas9wkz3uz3jcm4fe8ze57un0waejkwesc99waxsg0hff5q3ua4k4