crds:
  enabled: true
csi:
  cephFSKernelMountOptions: ms_mode=prefer-crc
  enableLiveness: true
  serviceMonitor:
    enabled: true
  provisionerReplicas: 1
enableDiscoveryDaemon: true
monitoring:
  enabled: true
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits: {}