apiVersion: v1
kind: Secret
metadata:
    name: firezone-secret
data:
    FIREZONE_TOKEN: ENC[AES256_GCM,data:NYI8Q9o3/Ir8075xOcPafLqb5GXpjJ4pbQviPlCkiKizqaZAS+9an2qdQ+1/TkKRYUVEai5RFbc0CZs5gh4nFBnUW9iwN2D4VtzjwgjoX1wWD8OO5YuFTus8xwjMh8bXaGnhLbi2Feiu8LU5XrZzLd3vPFkvmiv/vCIx7q0yAY/1d6oM2+eSrP9CZ7dl4j1X30zK2QzZTEEHeGOjNVvnKLzeUoEc99mGn+JrQWle0F5D+ejlDap4D9jTeVfpBB0LlHX4/nltcCgVnTe1QHu8YN0ldIAMbcz31yjM2Adw3o8dOK6v9b360J+EoTji6qXgwzQfqLlLrelsVWCUH9Iy0xCTDzLsDBoaFLj5jwvLQM6oizIy7LtZH1OpaYF99R9uu5Iq53b4PQexWlWmR2N8eRkajSPvfQLFJHRBTzhan44PNPtmZOiPcnxsbF3KSXjO9ZJnQ0FymXfpVr8rtcRbGWPwkd3vKEsn,iv:aksv1mXYiMja9Guq9SCT6wPjrXTo2MHX6JMGGyYmIo8=,tag:IBjPwh9GgBEIClIjaXyyVQ==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNXFDWXRKQllPblNrYlBh
            Z1BqMjRLVHRuajIzTkw4ZS9MQU5ITkRnUGhBCkJSR1VJalVaZi91UHM3WTNaczRP
            YWgyM09lSjcwcjVBZUVrR1E0RUdMeEkKLS0tIFZpYTg1U3UvRGQ1cmZOcHY1eHJj
            M3J0VytUL1hwbjFRWmFVWnVqZXpzTk0KLm6TfG3zfqPMDxTYYyqRywrrs+ytbNBc
            l6iz2LGgrxcOyGKQ6EDF9MK/xAd4lCBmPX+HEFQKbB59Ha172y1+FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T07:49:54Z"
    mac: ENC[AES256_GCM,data:mv+e2VOLIb3om/Rm95A+lchk7xWjCLwCEjTYqB1ULwM8k7ekXHM4vzEhIJ6pt2PPKptW2Pj1BavyLjg4er/go8Z51ZZEt/1g9E85BphdiDH4G6ksYY9GEjf/OoaCkvVLXEc/XAOGQ9o8RXg6iCIl/wKNXNMTH5MZeWaKvzJQVgU=,iv:Wx0pFIZpeuWr4hIzoB1j1mPPH80V4+CvtMZGGi+EpZU=,tag:gkmsqAnezpZs7S4dW5c+NA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
