global:
  env:
    - name: TZ
      value: Europe/Berlin

configs:
  cm:
    kustomize.buildOptions: '--enable-helm --enable-alpha-plugins --enable-exec'
  params:
    server.insecure: "true"

repoServer:
  env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: GNUPGHOME
      value: /home/argocd/.gnupg

  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-gpg
      secret:
        secretName: sops-gpg
    - name: gnupg-home
      emptyDir: {}

  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: ["/bin/sh", "-c"]
      args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools/;
          mv kustomize /custom-tools/;
          echo "Done.";
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    - name: import-gpg-key
      image: quay.io/argoproj/argocd:v2.13.2
      command: ["gpg", "--import","/sops-gpg/sops.asc"]
      env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
      volumeMounts:
        - mountPath: /sops-gpg
          name: sops-gpg
        - mountPath: /gnupg-home
          name: gnupg-home

  volumeMounts:
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /home/argocd/.gnupg
      name: gnupg-home
      subPath: .gnupg

