---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: radicale-configmap
    files:
      - ./resources/config
generatorOptions:
  disableNameSuffixHash: true
