apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:BApUbQELOkU7s/W7QdQlmJeVzEbrC0JEcIbQU2lIJLkgVPSsjwzM3uM/G7Os9gYmcIzeEZVha1qCjtWDRk27Cw==,iv:VuAQQ62fBPFdl+GPRenpWsJiSPvHsQFpti3jmA70Zkw=,tag:2Qm12PcVpxEQj9Ck2VSroQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZmZKblZpTUpwY25Ya245
            N0NwUnhOamFOa3VvWlAwSWpQcWg5eEVlbldFCnp6V1kxL25HT2tPWnZoTVRZdHpF
            bnVpWXdPcy9jRk5DT3VXZHV5bVhwaUUKLS0tIHlzcHBRSm9wdjNuL3lHbURFV0lN
            NFNxaTAza2FJOXJ5M2tMV2VsL1RIRFEKgCfjlIP0rLEVjn6/ORrva3atTGanzEF6
            FaYOsKzov2IDyrSpJwMqSwocFofnJxu9xKFKpLfSKdhe9XRFjQNDZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T10:51:27Z"
    mac: ENC[AES256_GCM,data:a6c3eV5aY4Y8wIjOHxxaGXCo/qhAqx4kN9f32aINM8cq/OoOT5jOFXqNcrkDiOuQjgNwLhmwv/oK+8BxyHIqOIKnv188psSp8xtO/tIsgc00b+aqE95cXmWUgs/Ki9wlHeaQkmO24lKarW+EZ4QshObFVZ4hSdjnypWfRYCqojQ=,iv:rPUF4KxETOQc/Qyn0l5SjTXId4yASXRcKH9h7yacxvs=,tag:gUE64ri+vyPppbXt/nFldg==,type:str]
    version: 3.13.1
