---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  evcc:
    containers:
      main:
        image:
          repository: docker.io/evcc/evcc
          tag: 0.204.0@sha256:89dfe02936e356e03049ed9f0ddb5f92d7f21b31179f6c1246f8eda8729be15c
        args: ["-c", "/config/evcc.yaml", "--disable-auth"]
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 10m

configMaps:
  evcc-config:
    data:
      evcc.yaml: |
        database:
          type: sqlite
          dsn: /data/evcc.db

defaultPodOptions:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "multus-iot",
        "interface": "eth1",
        "namespace": "multus",
        "ips": ["192.168.1.46/24"]
      }]
  securityContext:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: evcc
    ports:
      http:
        port: &port 7070

persistence:
  data:
    existingClaim: evcc-data-a
    globalMounts:
      - path: /data
  config:
    type: configMap
    identifier: evcc-config
    globalMounts:
      - path: /config

route:
  app:
    hostnames:
      - evcc.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: evcc
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
