---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  evcc:
    containers:
      main:
        image:
          repository: evcc/evcc
          tag: 0.203.1@sha256:bb2fa84b05fb170bd6524bf2452ccbd8a44dbbe3e63542b311c63ce43592ce0c
        args: ["-c", "/config/evcc.yaml", "--disable-auth"]
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 10m
      codeserver:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.99.2@sha256:6b5fcf74bb19579ca1666c8f96ac406ca5146a5c8756963a10991c4e520fa085
        env:
          TZ: Europe/Berlin
        args:
          [
            "--auth",
            "none",
            "--user-data-dir",
            "/config/.vscode",
            "--extensions-dir",
            "/config/.vscode",
            "--port",
            "12321",
            "/config",
          ]
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi

defaultPodOptions:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "multus-iot",
        "interface": "eth1",
        "namespace": "multus",
        "ips": ["192.168.1.46/24"]
      }]
  securityContext:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: evcc
    ports:
      http:
        port: &port 7070
      codeserver:
        port: &code-port 12321

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    retain: true

route:
  app:
    hostnames:
      - evcc.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: evcc
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
  codeserver:
    hostnames:
      - evcc-code.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: evcc
            port: *code-port
        matches:
          - path:
              type: PathPrefix
              value: /
