---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  vaultwarden:
    containers:
      main:
        image:
          repository: ghcr.io/dani-garcia/vaultwarden
          tag: 1.34.0@sha256:7747239abe2b6f8d5aa687bd138e007bbdcd8825795d1538e5f521ff83c37a29
        env:
          SMTP_HOST: sendmail.devpi.de
          SMTP_PORT: 587
          SMTP_SECURITY: "off"
          SMTP_FROM: server@devpi.de
          SIGNUPS_ALLOWED: "true"
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 10m

service:
  app:
    controller: vaultwarden
    ports:
      http:
        port: &port 80

persistence:
  data:
    existingClaim: vaultwarden-data-a

route:
  app:
    hostnames:
      - vault.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: vaultwarden
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
