---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  vaultwarden:
    containers:
      main:
        image:
          repository: ghcr.io/dani-garcia/vaultwarden
          tag: 1.33.2@sha256:87edb99945da91bd7504ac1435495595af2e89ad2c7adc151ae5bf091ec8baf2
        env:
          SMTP_HOST: postfix
          SMTP_PORT: 587
          SMTP_SECURITY: "off"
          SMTP_FROM: server@devpi.de
          SIGNUPS_ALLOWED: "true"
          ADMIN_TOKEN:
            valueFrom:
              secretKeyRef:
                name: vaultwarden-secret
                key: ADMIN_TOKEN
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 10m

service:
  app:
    controller: vaultwarden
    ports:
      http:
        port: &port 80

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true

route:
  app:
    hostnames:
      - vault.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: vaultwarden
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
