# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/library/common/values.schema.json
controllers:
  dispatcharr:
    pod:
      hostUsers: false
      resourceClaims:
        - name: gpu
          resourceClaimName: amd-gpu
    initContainers:
      chown-dbdir:
        image:
          repository: docker.io/library/alpine
          tag: "3.24"
        command:
          - /bin/sh
          - -c
        args:
          - |
            mkdir -p /data/db
            chmod 0750 /data/db
        securityContext:
          runAsUser: 0
    containers:
      app:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.27.2@sha256:f2b5ea3128b0513feb07efee7539ad546f3ba3a9095f19936f446f75b8baa894
        env:
          CELERY_BROKER_URL: redis://localhost:6379/0
          DISPATCHARR_ENV: aio
          DISPATCHARR_LOG_LEVEL: info
          DISPATCHARR_PORT: &port 9191
          REDIS_HOST: localhost
          TZ: Europe/Berlin
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            memory: 3Gi
          claims:
            - name: gpu

service:
  app:
    controller: dispatcharr
    ports:
      http:
        port: *port

route:
  app:
    hostnames: ["dispatcharr.devpi.de"]
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: longhorn-backup
    advancedMounts:
      dispatcharr:
        app:
          - path: /data
            subPath: data
        chown-dbdir:
          - path: /data
            subPath: data
  tmpfs:
    type: emptyDir
    advancedMounts:
      dispatcharr:
        app:
          - path: /tmp
            subPath: tmp
