apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
data:
    OPENVPN_USER: ENC[AES256_GCM,data:U0p1xGJiYNscMZdx,iv:QK2265wHAZLhc4MAICDkOawZqeEI7qY1XQzv7fE8ctA=,tag:OFDBXuvZRPdDlhCBPqg8Yw==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:nhHfFwsbdHUTPZ5BhLjUDw==,iv:B15N7YgqHGVpdw62u9MDW9WFtQxP6BZoeO3gm2LWwI0=,tag:cJMzGHgUcWJnz1Hyk139wg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:rSw3XWxQk49K6Wb8FhnpK1X9k05sArh5tX14Phz0NDOGSZ70rVb9KW5f5sKpZr1DXV3OgDNj+k/oJXL/,iv:AVTCY2XQqR1r5/AD/9i7UKAWhRfFoSLO4qzswCbAHjM=,tag:Wm1Zo/VVdu93fDiK4h+e2Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:18WWxFVHz3wFL/g8/ll/vKVsyJ9uT2jVy0GQtgbUB4zn23YUoakdUwkCktavO0Wx96aLyt5pa3HRcUXz,iv:gW/WXe0xBlo4jzBF2DCoSi+w0fldI/NTYsEQeuLzMQg=,tag:pHisju5hVIMS9gzkct+jjw==,type:str]
    VPN_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:dvESIQp/suOW0oCU,iv:pYXrCoW6JCtDNGGu0s+6zC45I5MedWK7lav+lplETLs=,tag:/giDs7vygbLCYwAGjsrYMA==,type:str]
    VPN_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:xnRdCC2i2RU8T8nlPrWRMw==,iv:B7a6WcsX8ATyCSfqSTTzVf1nWLqvFBh19fYark2CbjA=,tag:G7rNHXMYXQKGzIDCeFeAbg==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyN2MwUDJleEZ6aFZIanB1
            SE1xR1huVUVQWXZWYkZ3cjBuQUNVQ3RYK1NrCjdYU2hsSUNWUGhZMi9mL1g3OFUx
            U1BYUUVHbmx4N3pDUjlEcHJDc3ZBTUUKLS0tIGxBb0NDc2h6dVBBMkxrdmIrTEFm
            Y2tVZzZaUHdnM0xMeTNGU2VQSGhxUmsKxX1SjtbWsBxeGGLVMYo6aaVU6WkCtwwq
            Wozh6igIzZ7OQfA977iYgtiGvEyTQ/z2b8YiKO5REMwfRAC6D888hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T07:50:28Z"
    mac: ENC[AES256_GCM,data:VAdyOlRQeNHNbJHVhG3AnZehJRTFozxzqUc9WJeEcDfmBa/swaZFlYVm/vHecwhhnU3E6M1fsk40Ey5tUAZrD1+BdmorFofMkwWQ1FHZtPbuiV8MNZxP5reHHJgGell6EVXZ72fbByXzqOzbNQEA+/ruEql3zfUqzMZJsU/QrD4=,iv:btp6WdDHAgV79EvplmNCD3xqRvW8/KCkym0fEi45ONE=,tag:qqALs34YxaG0Wn14xMYE9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
