controllers:
  qbittorrent:
    type: statefulset

    pod:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    initContainers:
      coredns:
        image:
          repository: mirror.gcr.io/coredns/coredns
          tag: 1.12.1
        args:
          - -conf
          - /etc/coredns/Corefile
        restartPolicy: Always

      gluetun:
        dependsOn:
          - coredns
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0
        env:
          DOT: "off"
          DNS_ADDRESS: "127.0.0.2"
          VPN_SERVICE_PROVIDER: private internet access
          SERVER_REGIONS: "DK Copenhagen,Netherlands,DE Berlin"
          FIREWALL_INPUT_PORTS: 8080
          FIREWALL_OUTBOUND_SUBNETS: 10.245.0.0/16,10.244.0.0/16 # Allow access to k8s subnets
          PORT_FORWARD_ONLY: "true"
          VPN_PORT_FORWARDING: "on"
          VPN_PORT_FORWARDING_PROVIDER: private internet access
          VPN_PORT_FORWARDING_UP_COMMAND: |
            /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{"{{"}}PORTS{{"}}"}}}" http://qbittorrent.media.svc.cluster.local:8080/api/v2/app/setPreferences 2>&1'
        envFrom:
          - secretRef:
              name: qbittorrent-secret
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - (ip rule del table 51820; ip -6 rule del table 51820) || true
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"
        restartPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN

      vuetorrent:
        image:
          repository: alpine/curl
          tag: 8.12.1@sha256:edbbe6f64e9890474df2864d7ee92941bb03ce17b07fd9cadc1d14e9453fc031
        command:
          - /bin/sh
          - -c
          - |
            curl -L -o /vuetorrent/vuetorrent.zip \
              https://github.com/vuetorrent/vuetorrent/releases/latest/download/vuetorrent.zip && \
            unzip -o /vuetorrent/vuetorrent.zip -d /vuetorrent

    containers:
      app:
        nameOverride: qbittorrent
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.1.0@sha256:37aefd713ba31d51255995261616f1144378887bc5f21665a0ebf851fb85f69a
        env:
          TZ: Europe/Berlin
          QBT_WEBUI_PORT: &port 8080
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: qbittorrent
    ports:
      http:
        port: *port

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn-backup
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  downloads:
    existingClaim: media
    globalMounts:
      - path: /media/Downloads/qbittorrent
        subPath: Downloads/qbittorrent
  coredns:
    type: configMap
    identifier: qbittorrent-coredns
    advancedMounts:
      qbittorrent:
        coredns:
          - path: /etc/coredns/Corefile
            subPath: Corefile
            readOnly: true
  vuetorrent:
    type: emptyDir

route:
  app:
    hostnames:
      - qbittorrent.devpi.de
      - qb.devpi.de
      - download.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

configMaps:
  qbittorrent-coredns:
    data:
      Corefile: |
        .:53 {
            bind 127.0.0.2
            rewrite stop type AAAA A
            errors
            health :8081 {
                lameduck 5s
            }
            log {
                class error
            }
            forward . tls://9.9.9.9 tls://149.112.112.112 {
                tls_servername dns.quad9.net        
                policy sequential
                health_check 5s
            }
            reload
        }

        cluster.local:53 {
            bind 127.0.0.2
            rewrite stop type AAAA A
            errors
            log {
                class error
            }
            forward . 10.245.0.10
        }
