controllers:
  qbittorrent:
    initContainers:
      coredns:
        image:
          repository: mirror.gcr.io/coredns/coredns
          tag: 1.12.2
        args:
          - -conf
          - /etc/coredns/Corefile
        restartPolicy: Always

      gluetun:
        dependsOn:
          - coredns
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.40.0
        env:
          DOT: "off"
          DNS_ADDRESS: "127.0.0.2"
          VPN_SERVICE_PROVIDER: private internet access
          SERVER_REGIONS: "DK Copenhagen,Netherlands,DE Berlin"
          FIREWALL_INPUT_PORTS: 8080,3000
          FIREWALL_OUTBOUND_SUBNETS: 10.245.0.0/16,10.244.0.0/16 # Allow access to k8s subnets
          PORT_FORWARD_ONLY: "true"
          VPN_PORT_FORWARDING: "on"
          VPN_PORT_FORWARDING_PROVIDER: private internet access
          VPN_PORT_FORWARDING_UP_COMMAND: |
            /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{"{{"}}PORTS{{"}}"}}}" http://qbittorrent:8080/api/v2/app/setPreferences 2>&1'
        envFrom:
          - secretRef:
              name: qbittorrent-secret
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - (ip rule del table 51820; ip -6 rule del table 51820) || true
        resources:
          requests:
            squat.ai/tun: "1"
          limits:
            squat.ai/tun: "1"
        restartPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_ADMIN

    containers:
      app:
        nameOverride: qbittorrent
        image:
          repository: ghcr.io/home-operations/qbittorrent
          tag: 5.1.2@sha256:a724f86a39fa637fc4ff81165585d7273dc9dcd9ca59818a34e9fa9c467dd26c
        env:
          TZ: Europe/Berlin
          QBT_WEBUI_PORT: &qbit_port 8080
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 4Gi

  vuetorrent:
    containers:
      app:
        image:
          repository: ghcr.io/vuetorrent/vuetorrent-backend
          tag: 2.5.1@sha256:bd7cb19459a664073a05e8c4c8482888a2f41f307aa2fce2b1d329e35db7b358
        env:
          QBIT_BASE: http://qbittorrent.media.svc.cluster.local:8080
          PORT: &vue_port 3000
          SKIP_X_FORWARD_HEADERS: true
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: qbittorrent
    forceRename: qbittorrent
    ports:
      http:
        port: *qbit_port

  ui:
    controller: vuetorrent
    ports:
      http:
        port: *vue_port

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn-backup
    advancedMounts:
      qbittorrent:
        app:
          - path: /config
  downloads:
    existingClaim: media
    globalMounts:
      - path: /media/Downloads/qbittorrent
        subPath: Downloads/qbittorrent
  coredns:
    type: configMap
    identifier: qbittorrent-coredns
    advancedMounts:
      qbittorrent:
        coredns:
          - path: /etc/coredns/Corefile
            subPath: Corefile
            readOnly: true
  vuetorrent-config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: longhorn-backup
    advancedMounts:
      qbittorrent:
        vuetorrent:
          - path: /config
route:
  app:
    hostnames:
      - qbittorrent.devpi.de
      - qb.devpi.de
      - download.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - identifier: ui
            port: *vue_port
        matches:
          - path:
              type: PathPrefix
              value: /

configMaps:
  qbittorrent-coredns:
    data:
      Corefile: |
        .:53 {
            bind 127.0.0.2
            rewrite stop type AAAA A
            errors
            health :8081 {
                lameduck 5s
            }
            log {
                class error
            }
            forward . tls://9.9.9.9 tls://149.112.112.112 {
                tls_servername dns.quad9.net
                policy sequential
                health_check 5s
            }
            reload
        }

        cluster.local:53 {
            bind 127.0.0.2
            rewrite stop type AAAA A
            errors
            log {
                class error
            }
            forward . 10.245.0.10
        }
