---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json

controllers:
  home-assistant:
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: 2026.8.3@sha256:16ca445e58fa71d4f7ff287d4e9793ea690ccae932a5e200852371425cd7abb0
        env:
          TZ: Europe/Berlin
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 800M
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
      codeserver:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.132.0@sha256:b88ed46a6ace76a0294a17a24f39aa88032ed0a3692c3d8ab5433b47ab57ccbf
        env:
          TZ: Europe/Berlin
        args:
          [
            "--auth",
            "none",
            "--user-data-dir",
            "/config/.vscode",
            "--extensions-dir",
            "/config/.vscode",
            "--port",
            "12321",
            "/config",
          ]
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi

defaultPodOptions:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "iot",
        "namespace": "multus",
        "ips": ["192.168.1.45/24"],
        "mac": "32:d0:8d:e8:14:a6"
      }]
  securityContext:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch

persistence:
  config:
    existingClaim: homeassistant-data-a
  config-logs:
    type: emptyDir
    globalMounts:
      - path: /config/logs
  config-tts:
    type: emptyDir
    globalMounts:
      - path: /config/tts
  tmp:
    type: emptyDir
route:
  app:
    hostnames:
      - hass.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: home-assistant
            port: &port 8123
        matches:
          - path:
              type: PathPrefix
              value: /
  codeserver:
    hostnames:
      - hass-code.devpi.de
    parentRefs:
      - name: web-internal
        namespace: cilium
        sectionName: https
    rules:
      - backendRefs:
          - name: home-assistant
            port: &code-port 12321
        matches:
          - path:
              type: PathPrefix
              value: /
service:
  app:
    controller: home-assistant
    ports:
      http:
        port: *port
      codeserver:
        port: *code-port
