apiVersion: v1
kind: Secret
metadata:
    name: external-dns-bind-secret
type: Opaque
stringData:
    tsig_secret: ENC[AES256_GCM,data:3FjUdlsBabyjFrvMkWGvCytG8CkWVyJFb0UTXQQz5qs+7mk2YfxQemq3RD4=,iv:Z63xf6e9LeiRcyhe2vQa60Bf3rjS7CV1PKLfsE8x0Ag=,tag:lzgz7c1CcCuxmdSNIwcV2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUWhSbGlWOG9IUWt0QjVv
            blhaQlJlWkJWamVWVHduNGtRU2R3ZHFEM2t3CnJiRncvdUxIZm5xVHNIc1daYi9Z
            dWw5dXR1WUlIOFF5SVdOQ1JPdE90R1UKLS0tIFYxRkJKOWVObStLd1JnUzNFZCtz
            clpNZlZJcmo1SmZ5NXVuRnNmSkhKTGsKPkuRjypbqtzu9XS2QE44CFdh+XXwKUmh
            +leNIzTUqIKADM7uJNkTeUChCRMEodtyQhuyR0/BqF7JpEk+CwqnYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T21:08:27Z"
    mac: ENC[AES256_GCM,data:0jUMI12xrsUXbO6W0TqUqr3Q1ZAtf7u6mJjQiEjzqdrYsS/TbTNSGKw5DHxnLO6jeRBtqOFbKYzikM4Mo24yMShA6cNIhjbPKhNY6k8oc1C4JW2qPW1pCYIIX7aUkMYTTtwl2RBfTDZJ5PDPvJGdenHH3ToG7Dq9KCmdJiYA52c=,iv:v+v0jpzWfdwsnDs0Ae/02q7UqJpTvCg5J8XLaeZg6S0=,tag:bsulb4euouQVCSne8zQE/A==,type:str]
    version: 3.13.1
