domainFilters:
  - devpi.de
extraArgs:
  - --webhook-provider-url=http://localhost:8888
policy: sync
provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v9.0.1
    env:
      - name: DRY_RUN
        value: "false"
      - name: LOG_LEVEL
        value: debug
      - name: ADGUARD_URL
        value: http://192.168.1.1:8080
      - name: ADGUARD_USER
        value: admin
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-adguardhome-secret
            key: external_dns_password
    ports:
      - containerPort: 8080
        name: http-webhook
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    securityContext:
      readOnlyRootFilesystem: true
resources:
  requests:
    cpu: 16m
    memory: 90M
  limits:
    memory: 90M
sources:
  - service
  - gateway-httproute
triggerLoopOnEvent: true
txtOwnerId: main
txtPrefix: "k8s."
