apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: paperless-web
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "paperless.lan"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: paperless-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paperless-redirect
spec:
  parentRefs:
    - name: paperless-web
      sectionName: http
  hostnames:
    - paperless.lan
  rules:
  - filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect