apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: paperless-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.devpi.de"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.devpi.de"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: paperless-cert
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paperless-redirect
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: paperless-web
      namespace: paperless
      sectionName: "http"
  hostnames:
    - "archiv.devpi.de"
  rules:
  - filters:
      - requestRedirect:
          scheme: https
          statusCode: 301
        type: RequestRedirect
    matches:
      - path:
          type: PathPrefix
          value: /