clients:
  qb:
    download_path: /media/Downloads/qbittorrent
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.media.svc.cluster.local:8080

bypassIgnoreIfUnregistered: true

filters:
  default:
    MapHardlinksFor:
      - retag
    ignore:
      - IsTrackerDown()
      - Downloaded == false
      - SeedingHours < 26
      - HasAnyTag("permaseed")
      - Label in ["manual"]
      - HasAnyTag("expired") == false
    remove:
      - IsUnregistered()
      - HasAnyTag("not-linked", "episode")
      - HasAnyTag("site:TL", "site:YSC", "site:ST")
    tag:
      - name: added:1d
        update:
          - AddedDays < 7
      - name: added:7d
        update:
          - AddedDays >= 7 && AddedDays < 14
      - name: added:14d
        update:
          - AddedDays >= 14 && AddedDays < 30
      - name: added:30d
        mode: full
        update:
          - AddedDays >= 30 && AddedDays < 180
      - name: added:180d
        update:
          - AddedDays >= 180
      - name: not-linked
        update:
          - HardlinkedOutsideClient == false
      - name: site:ANT
        update:
          - TrackerName == "anthelion.me"
      - name: site:AR
        update:
          - TrackerName == "alpharatio.cc"
      - name: site:BLU
        update:
          - TrackerName in ["blutopia.cc", "blutopia.xyz"]
      - name: site:FNP
        update:
          - TrackerName == "fearnopeer.com"
      - name: site:FL
        update:
          - TrackerName in ["filelist.io", "thefl.org"]
      - name: site:HDS
        update:
          - TrackerName == "hd-space.pw"
      - name: site:HDT
        update:
          - TrackerName == "hdts-announce.ru"
      - name: site:IPT
        update:
          - TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]
      - name: site:MLK
        update:
          - TrackerName == "milkie.cc"
      - name: site:MTV
        update:
          - TrackerName == "morethantv.me"
      - name: site:OE
        update:
          - TrackerName == "onlyencodes.cc"
      - name: site:PHD
        update:
          - TrackerName == "privatehd.to"
      - name: site:RFX
        update:
          - TrackerName == "reelflix.xyz"
      - name: site:ST
        update:
          - TrackerName == "scenetime.com"
      - name: site:SP
        update:
          - TrackerName == "seedpool.org"
      - name: site:TD
        update:
          - TrackerName in ["jumbohostpro.eu", "td-peers.com"]
      - name: site:TL
        update:
          - TrackerName in ["tleechreload.org", "torrentleech.org"]
      - name: site:UHD
        update:
          - TrackerName == "uhdbits.org"
      - name: site:YSC
        update:
          - TrackerName == "yu-scene.net"
      - name: expired
        update:
          - (TrackerName != "anthelion.me" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "alpharatio.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "blutopia.cc" && TrackerName != "blutopia.xyz" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "fearnopeer.com" || SeedingDays > 30.1)
          - (TrackerName != "filelist.io" && TrackerName != "thefl.org" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "hd-space.pw" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "hdts-announce.ru" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "bgp.technology" && TrackerName != "empirehost.me" && TrackerName != "stackoverflow.tech" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "milkie.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "morethantv.me" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "onlyencodes.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "privatehd.to" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "reelflix.xyz" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "scenetime.com" ||  SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "seedpool.org" || SeedingDays > 10.1 || DownloadedBytes == 0)
          - (TrackerName != "jumbohostpro.eu" && TrackerName != "td-peers.com" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "tleechreload.org" && TrackerName != "torrentleech.org" || SeedingDays > 10.1 || Ratio > 1.01  || DownloadedBytes == 0)
          - (TrackerName != "uhdbits.org" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "yu-scene.net" || SeedingDays > 5.1 || DownloadedBytes == 0)
      - name: episode
        update:
          - len(Files) <= 3 && (Label in ["tv-sonarr"] || HasAnyTag("tv-sonarr.cross-seed"))
      - name: tracker-down
        update:
          - IsTrackerDown()
      - name: unregistered
        update:
          - IsUnregistered()
