clients:
  qb:
    download_path: /media/Downloads/qbittorrent
    enabled: true
    filter: default
    type: qbittorrent
    url: http://qbittorrent.media.svc.cluster.local:8080

bypassIgnoreIfUnregistered: true

filters:
  default:
    MapHardlinksFor:
      - retag
    ignore:
      - IsTrackerDown()
      - Downloaded == false
      - SeedingHours < 26
      - HasAnyTag("permaseed")
      - Label in ["manual"]
    remove:
      - IsUnregistered()
      # Remove not linked and expired
      - HasAllTags("not-linked", "hnr:immune")
      # Remove single tv episodes and older than 14 days (prefer season packs) and expired
      - len(Files) <= 3 && ( Label in ["tv-sonarr"] || HasAnyTag("tv-sonarr.cross-seed") ) && AddedDays >= 14 && HasAnyTag("hnr:immune")
      # Remove prune and expired
      - HasAnyTag(hnr:immune) && (HasAnyTag("prune:14d") && SeedingDays > 14 || HasAnyTag("prune:7d") && SeedingDays > 7)
    tag:
      - name: added:1d
        update:
          - AddedDays < 7
      - name: added:7d
        update:
          - AddedDays >= 7 && AddedDays < 14
      - name: added:14d
        update:
          - AddedDays >= 14 && AddedDays < 30
      - name: added:30d
        mode: full
        update:
          - AddedDays >= 30 && AddedDays < 180
      - name: added:180d
        update:
          - AddedDays >= 180
      - name: not-linked
        update:
          - HardlinkedOutsideClient == false
      - name: site:ant
        update:
          - TrackerName == "anthelion.me"
      - name: site:ar
        update:
          - TrackerName == "alpharatio.cc"
      - name: site:blu
        update:
          - TrackerName in ["blutopia.cc", "blutopia.xyz"]
      - name: site:fnp
        update:
          - TrackerName == "fearnopeer.com"
      - name: site:fl
        update:
          - TrackerName in ["filelist.io", "thefl.org"]
      - name: site:hds
        update:
          - TrackerName == "hd-space.pw"
      - name: site:hdt
        update:
          - TrackerName == "hdts-announce.ru"
      - name: site:ipt
        update:
          - TrackerName in ["bgp.technology", "empirehost.me", "stackoverflow.tech"]
      - name: site:mlk
        update:
          - TrackerName == "milkie.cc"
      - name: site:mtv
        update:
          - TrackerName == "morethantv.me"
      - name: site:oe
        update:
          - TrackerName == "onlyencodes.cc"
      - name: site:phd
        update:
          - TrackerName == "privatehd.to"
      - name: site:rfx
        update:
          - TrackerName == "reelflix.xyz"
      - name: site:st
        update:
          - TrackerName == "scenetime.com"
      - name: site:sp
        update:
          - TrackerName == "seedpool.org"
      - name: site:td
        update:
          - TrackerName in ["jumbohostpro.eu", "td-peers.com"]
      - name: site:tl
        update:
          - TrackerName in ["tleechreload.org", "torrentleech.org"]
      - name: site:uhd
        update:
          - TrackerName == "uhdbits.org"
      - name: site:ysc
        update:
          - TrackerName == "yu-scene.net"
      - name: hnr:immune
        update:
          - (TrackerName != "anthelion.me" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "alpharatio.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "blutopia.cc" && TrackerName != "blutopia.xyz" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "fearnopeer.com" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "filelist.io" && TrackerName != "thefl.org" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "hd-space.pw" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "hdts-announce.ru" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "bgp.technology" && TrackerName != "empirehost.me" && TrackerName != "stackoverflow.tech" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "milkie.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "morethantv.me" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "onlyencodes.cc" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "privatehd.to" || SeedingDays > 14.1 || DownloadedBytes == 0)
          - (TrackerName != "reelflix.xyz" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "scenetime.com" ||  SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "seedpool.org" || SeedingDays > 10.1 || DownloadedBytes == 0)
          - (TrackerName != "jumbohostpro.eu" && TrackerName != "td-peers.com" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "tleechreload.org" && TrackerName != "torrentleech.org" || SeedingDays > 10.1 || Ratio > 1.01  || DownloadedBytes == 0)
          - (TrackerName != "uhdbits.org" || SeedingDays > 7.1 || DownloadedBytes == 0)
          - (TrackerName != "yu-scene.net" || SeedingDays > 5.1 || DownloadedBytes == 0)
      - name: tracker-down
        update:
          - IsTrackerDown()
      - name: unregistered
        update:
          - IsUnregistered()
