clients:
    qb:
        download_path: ENC[AES256_GCM,data:cCfACnpDJwalyPmOxGAzHRRpIek+E1urqMV5qg==,iv:x3SorD1xajBxiav42czzJxPZC5P1sOcOfWfV1FUfffw=,tag:T7TeTty7FXwvGkbTiWemhw==,type:str]
        enabled: ENC[AES256_GCM,data:1LDptA==,iv:0ZwGroR7qPYojsN9sW1Jf1HhcksA7U1q1YXvZH+Novg=,tag:zZHdEiqeaxOnZIKFX3catA==,type:bool]
        filter: ENC[AES256_GCM,data:NlNMaCJQ0w==,iv:5P7PQyxKEFC731ITTrSew4MCxrJqLxHgJiZyQlnUVes=,tag:OWCuJY6fih04RDcY2XxyBA==,type:str]
        type: ENC[AES256_GCM,data:p1LrlSE/GR5L/ws=,iv:Utrm20JUpZmntiCUviqqGnewlmnHyV7d3h0D4Rljgro=,tag:PH10ghCatrFpPrTI0HD/YA==,type:str]
        url: ENC[AES256_GCM,data:dzRCXWuBYB9XZjuyr75C905ycXVV9rj84/e4f4XfDofhZ6NWFhgvmkTqrEMAZLw=,iv:r1h940DdRTXxOXTlvcSpsuMXNu2F09fEgOb+2y+8VIc=,tag:7xBlxE/gMNt23VYGfxjSng==,type:str]
filters:
    default:
        MapHardlinksFor:
            - ENC[AES256_GCM,data:XZxMOEo=,iv:CeFlq70BsnVX694lwQlg0VTYDEvGa0++08h3suEMavM=,tag:YCYl+koeYk6sSkEIWdNi9A==,type:str]
        ignore:
            - ENC[AES256_GCM,data:FJTTP2elmopxUMMwTlz4,iv:ZLboELQ/E23Z7dTN8B+ZLy8yBzFpvfqdqbsnJ7bJhmE=,tag:j3VEI7YIhHREdUz5guEerA==,type:str]
            - ENC[AES256_GCM,data:8b37IGA1NQyxUCrFyz/gdWsIX2ZVibRGPqv+mUSrA7ki9VC2BPAYow==,iv:ZQyYlLDm/xSD8S5xrC1fwpTBJuHEDc1AEjN6XCoGrdU=,tag:/fx2DBJmTptpe2jXRjCd1g==,type:str]
            - ENC[AES256_GCM,data:dJFvNbeWIzdhAzQnHHxbMnLLESHjLZrHW6t3H/+7Mx59Ot/hdBg=,iv:IqVbKpK1//PmEWkaZn7FoTK0ZdlRHChMVPglIpnWITg=,tag:ADm/x0wSk7bWtFP4S2rQDQ==,type:str]
        remove:
            - ENC[AES256_GCM,data:kRdUQNTtyw1dHdRZq4T/RA==,iv:6za6wT/r4RMqPzL9HBKZJU1lwQiQdNY4JdDReGaoy60=,tag:drUtnTXX/syhp6YU85tbjw==,type:str]
            - ENC[AES256_GCM,data:GrRigDb8GSDzs1scGKTyiSPM9UM+Kt3DOqJ9AMyViIH6r4DMfEfyFHdMt0oMPxV9EqfoHhUHYGomJ/INwJypQi8S4g==,iv:D0cr57Ziv8raMIwQVebRZ2nes4bfCvpKxN9qarNmnn4=,tag:fod1LdR0/eFRSVjKBfArww==,type:comment]
            - ENC[AES256_GCM,data:gL98RJqIonIsU9iQRKbb+0041bFvlKiP1wERXSNKbCsCg/6ISuUIm4nAfJSwSaP8+nFBdb+QBJQ75vDH9wolHmBYhqANPFjVDc3cC7NjIiCayEBkX8O1i8V5YDdzSG4eBBCHtxbYH5FeSp+wqW1F2aq4oJN3qbm9izbqigW+RSj7RauHnB9Sh8VB2yjaHznYghhKoghhmkR6iGVt3KFM2fEx03Y1NhWrIiJy0vSs0k4=,iv:saKavFLkiDC+NQ92p4QwoQUuWt5UpMfbxlzzF4zO57Y=,tag:qm0MamH7fwodbuk12aMp8A==,type:str]
            - ENC[AES256_GCM,data:LtKPF8QcwQchnCVdVZlSYsCx6YuaAgGKNLsk3qFcEKV25zGkmmaD7A6pToCLggmDFkGdmj9eo8DC4j35dg==,iv:OahrABJfmzRKjgN29YtdGFcRNvhg/6XEHpb2LyKNnLY=,tag:yfQfNY+ymCE6z7Zq6qNrtA==,type:comment]
            - ENC[AES256_GCM,data:Ko+ZJPEJUNyGu0kh93enlsSbsfphJAgV7BPUrF69bIh+7XN+wqjpPV32IeXNW14Oov01Kg3ha61uhftUucB6I/f3BMabW33H43VnZ0/zgwQL9ON5NV+MjBmYfxQePB05r5mOEtkgFGshNArPrHn0zHuzw89yhs5KkOcb2nWgYpBmAU9sgcSkL5Pg7UQFV/ZxeYmM955RDJIQKiIQ5D8r9+JN8m68V2ILLEgk/0eVV0ISBUb8vivmX9RvJif6//iqS6U4o82CBJqZOpwrX001eA==,iv:WPT/OQZEvGKXeuxoc70J+XuG11MQLlIbHtRqVu2c4wo=,tag:KIRf5rhRmE83JJuvZBkb+A==,type:str]
        tag:
            - name: ENC[AES256_GCM,data:1HR+1nr/8Vw=,iv:A/Bb/y21TLR8vq2haYaEbj/JBVkxDTWIG/0PAyf4XZY=,tag:+LiAkHpCjxXyap8RDBkvQA==,type:str]
              mode: ENC[AES256_GCM,data:tLFp9A==,iv:lxbEQyXU3li8s6tj0AoztTz23yQFH742vmLapk4tIPk=,tag:qxgclMJNJKimoGOZZt7nqA==,type:str]
              update:
                - ENC[AES256_GCM,data:3/O69V+LmrtmTneF0w==,iv:woTXhTwXb5nNUaLuExmBqvajSOY2QZJbZxw9Xy2Vu5M=,tag:sdzXhtaGAvsMhYmDxVZyNg==,type:str]
            - name: ENC[AES256_GCM,data:PQYtF0tJbzE=,iv:aYRmGLxbeCpFseU67pdnlcHuZwTafj07GW2FjaBqO3Q=,tag:ntkThAZ8pt2akjP+Ot8KBA==,type:str]
              mode: ENC[AES256_GCM,data:/pDwlQ==,iv:fZCuaGPjSeUMtzXWPrSc0cI07HmWGjiriphlFanhz7g=,tag:hNdk4pqvjQ6w6isQtfpxEA==,type:str]
              update:
                - ENC[AES256_GCM,data:15SoFaVWocVLQZ3fLqTu7rDnIwI2XdCOu2w0sQMyFXE=,iv:fiy7rPOJ6mlyGNLNy6m8dkvQPQxFR7xU5W9pH132lR0=,tag:c0oUMtUbfFcFGeKByfJYJA==,type:str]
            - name: ENC[AES256_GCM,data:u0McwoJWREnU,iv:8oi9zn7Gmpao64Pc8wKmbZX9sWi3rK7lIiMGxxqRqGk=,tag:g5ePPUhyXudWtLb0xXlnuA==,type:str]
              mode: ENC[AES256_GCM,data:zZqAOQ==,iv:NvUsD3SVVX2W0SA2aplEpIF08nKbLWKIAH2YQiPnOqU=,tag:LB8SwUqPAh9NBXN5OWpS/A==,type:str]
              update:
                - ENC[AES256_GCM,data:4d6g0HW4GX31X0a4vXCZmSG8gq5sa1rAVGyv2SSc6rXk,iv:ZDnAFNl4b9Cp/VJ39RkJOo+2oCOvqvXzwjmIw2b66pg=,tag:OMKAg9M5XbPFx1mj4XV4sw==,type:str]
            - name: ENC[AES256_GCM,data:l6aSJBPNkGjE,iv:vRYMzdSxGZvPaAhqtJAZTwydfSLByqRF97zZ4BNE/Rs=,tag:wexDjRjSQHb6awBcAXFpTg==,type:str]
              mode: ENC[AES256_GCM,data:UCHbng==,iv:UeErUIWBQpno2QGxkgdHk83KjHC2mjzgFoYeJauSP5Y=,tag:cd29UehnxcL1wrwqvohmCA==,type:str]
              update:
                - ENC[AES256_GCM,data:Z1BmgWuJzziwVYuLIEpMNVU7/mIytdbWhzO1B4hsc+nsJw==,iv:/z8LqzZBK6NIJeDsx13rWBfDnVIKXC28F9tbIAHEWco=,tag:wh9RdjbTAR23sPOXJ6KBSw==,type:str]
            - name: ENC[AES256_GCM,data:EOnVPrLxvWk7tQ==,iv:bXByhMH609d59RI6G3SQ5EcVVwE7oRsGCYXx4ulpJGc=,tag:1DAe2Tp6P03ENLsWRcoLjg==,type:str]
              mode: ENC[AES256_GCM,data:4nYOGA==,iv:nQfJ7UIfOIXDihAXU2mkv7SvR+drLQhl01elYTd7ZZs=,tag:YCi3wWzJrOr5K5UyK8zH9w==,type:str]
              update:
                - ENC[AES256_GCM,data:b3tCMXn4CUe4QLRifItdmw==,iv:KyJavwItx/ADz18kBq1CpSN5NZ6nbCLcOpt8VLAP8xU=,tag:S8ayqrU4hz9wCqq3/vEJPg==,type:str]
            - name: ENC[AES256_GCM,data:lvuRUp3ULkDPYQ==,iv:fA3lvuzgoTzQtymHqxpZblPJbJaFBJq25t+gK42RYaM=,tag:QwG/9FxaPcMkmPpE8LOCpQ==,type:str]
              mode: ENC[AES256_GCM,data:q8GOVw==,iv:A/LXQZSRcVtEkIJ6HENdKM0YY6dhSbYSE6O4DBfDl4c=,tag:b1lOTdgED2jiawAjeZoOgg==,type:str]
              update:
                - ENC[AES256_GCM,data:2/4ad5wj9r81mA7+3soFexwCdQ0gw3YriXAS7yrImct9Ceu5RM2JpXwfwt3Yo29Vn0VgNNGpxPcWOyW0RWROawytaV2loGpR8m7Z9HlUq9IKa9edDNGzjMA5RqGR,iv:6J8oFl4ekDX7Hkk8v6NlaEeuampG4wEDgiwGrkKxSnY=,tag:y+5E1tQvkopReel9lN19Vw==,type:str]
            - name: ENC[AES256_GCM,data:jJQKGFbxQXk=,iv:xBz9IXWPP/RInSlt3G8ivA7Cx/mIHPQfAjFcYkvP0SM=,tag:hbIIQ+0lFmEDAlW448d76A==,type:str]
              mode: ENC[AES256_GCM,data:veX9Cg==,iv:/RbWKTVERv1HCDtPUmJlKJU52jxconJ40l4hez5ecMY=,tag:WvYtX5cAnMSQO7LFcqqNEg==,type:str]
              update:
                - ENC[AES256_GCM,data:I0NhOoViJabD7F7QHFdz5qFuFPYkIx02hRKj7J7BDQ==,iv:+FAWOHDXfu6wzFtNzR1LJMaGRcRrF+AWguX0Hh2msRE=,tag:UEsR6cMbHa5GoxGTXKu3Sw==,type:str]
            - name: ENC[AES256_GCM,data:fHcuikizqA==,iv:PH/D8daV4CCTiDiDRV9ViDlk/rGT0ZJxbyDmC75WQNU=,tag:EDv4JOS3PCBnmUrO5bpJjg==,type:str]
              mode: ENC[AES256_GCM,data:k+yNCQ==,iv:A9EUIOhFmK+wPrzbnTgBG5pQ3PDuImQs8l5CkR7/1wg=,tag:MylGKASARnnnc4fqffSd5Q==,type:str]
              update:
                - ENC[AES256_GCM,data:KMdvm1gQoHdQovtFHa1kp/XBakB1EPe50jK54Ww=,iv:08m7uZ8NEbEfMvB2QHiOKparjT5J0PAuhsuNanzDUmI=,tag:KqffdbgeiJmsSJ6LIovJMA==,type:str]
            - name: ENC[AES256_GCM,data:qIDQ8M1lyQbG,iv:4YQrcRHylZ3vbsuKKhTe+/IaRbNQX5QaRIKVSs3krS0=,tag:gmdj1M+g8XgxtwR+vtrWMw==,type:str]
              mode: ENC[AES256_GCM,data:TVtKXQ==,iv:gCufXsQvzOzM7z2mt31BBMsU+B0n1SvF2iEnV9j60r0=,tag:Kw7DR248td+51gaFoQZ+qw==,type:str]
              update:
                - ENC[AES256_GCM,data:BkHpwr03Bu2DFIItIgSXMRmrWD3Zs11D+k5Ee5U=,iv:htybqkcyU5uYwpo9GA+oufvf3sg2p3OeXXlxgieoChA=,tag:bE3meTQergLPLUb6ZtMWgA==,type:str]
            - name: ENC[AES256_GCM,data:79Gu2Jpq2lUci8tY,iv:pIbP52l1PyXYrlszcGUrAllYwnrkb8k0L0CrE0qSfPg=,tag:nk4ryn2KCvpcI4kWOGGBHQ==,type:str]
              mode: ENC[AES256_GCM,data:0sl3Sw==,iv:5e27g9w+lndvCe2Kjf4+fS0NgaWRhjAjNGmrHgXunzk=,tag:EI84cMyY5H8o+n+c5USodA==,type:str]
              update:
                - ENC[AES256_GCM,data:mOfV9iAKcguHJshCIqEs,iv:DourXDewx4KCK2Q3C2QG0EqJ60sSXsa3RMfPcr951/Y=,tag:KKNarYKM+TnDAhL2Gi4xKg==,type:str]
            - name: ENC[AES256_GCM,data:LXqom+rLdOHGbM+J,iv:nvOvVWgIXuHTdkKWV+Rt9yVT4YRmjaaBa0fYOXISLqs=,tag:cx7eZrAIAS4/xwLkHQiMFw==,type:str]
              mode: ENC[AES256_GCM,data:Gm6Xsg==,iv:EF5+JsRgPNRmjLChwSnmm4YU2PUt2i6UjyOnB/NXMR0=,tag:0jil1/FdAbPcs03Ng9GWcA==,type:str]
              update:
                - ENC[AES256_GCM,data:abFo4q9ASfzP0XbesJgDxQ==,iv:x6UZ4Qj4cGlVTrEaFb8KalIdTxmFF2BHnygnrhZNQ3Y=,tag:ut4mI8DjdKR8l+RBUKlxjw==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZW5tNVJOenFtVjYwZUlr
            NldGci9WdXpOeHllbk9paE5NRUJtZmdWZVh3Ck9ZdzE3enJnRmZXK3BZdUovWnF1
            emM5cW9mMy9qWmtUbUdEWnhtekxwdnMKLS0tIE1oWkJuMGsyVlFDa1doUUErNXBQ
            bnFCellpYnhuMjB0d1VEakwyZFpZV0kKVXPkkEKz6Zh7rGrqzO5c4jcFDDKOrcRu
            g462XhSCoj97a3Vhjm55ZWNhqEbCGmKDu0Xl1jnUaLTt7JYDhbHq+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-25T07:07:05Z"
    mac: ENC[AES256_GCM,data:SWeroOokyxvRwXXtHud6YDe226wciFVR7Q5DHcUtAs61IEOwP2QGYGs8sBYaNfMWIWy4H/pp6/dT2qRBSxlI8/CK/wxjeZC1w6bYJLRsYnIfMvn0ARmVyhrAmLm9xAkzJiVD/JXjRtM3JVPLKGb6oeguA64MS6WVBhh/Tun6vZw=,iv:9VsJpNbZXTA+raB9D5pfhuGP9d3Ut4DWuRlOQag2ySE=,tag:Pa36pCH5kyZiViETokKt5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
