apiVersion: v1
kind: ConfigMap
metadata:
    name: qbtools-config
data:
    config.yaml: ENC[AES256_GCM,data:ZqT+V2MckW9sc3OrUR9tyaRih4Nli8OVRzdc9vHatlUJV0OGR6y2+IFIlrfmGzFTofejx2iX4WnJEnpIU8r31Fo0TEogao/brHoxkLpeOqDz3+p2RazlbvmwrhpIav+0ADqzYPRJEZoU0odnHSse075JKc3hms7HN12OeXwcR7MOKYaElsGm3zIe8viOZ9/KKtcy2whFJnFmbTNGHZoBBpMkoqKEBRUrdaI=,iv:bEtUBbgNpG/v7b7MMahlP98NgQPxcCp+/tzoGxXA50c=,tag:ozWbQJmUVq9vWTZrRAvuuw==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNEV1ZW8xaGVUVStTL0VL
            SEhib0N5RzZyOTBXZFI4ZU1ORmZLbHkzbno0CkVlSmNhaWVvUkFzZjY5ejg2NEk4
            bnYwTkJWTTNXTjFDNVJwcDlxRUhBTFUKLS0tIHpZWEprc1pTbnozT0lYcElyM0hZ
            bW9XYi9CQjBHQ0dKT1BoWUw2dm1jWnMK2Hc07k3/n9fL7KgHA6UF3ComNizSy5+K
            ugCEz9AviTPk7JZh7k2dwSDpozll8q6JUlhKdRsfncaZzMmMyvw+mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-06T18:31:47Z"
    mac: ENC[AES256_GCM,data:1G+BApv8vnTrWTjBuKJVDaIE5ICxpQSs673AoCYmjerl5609kUT98N+wZfhfLoGIvfyTS1nUPi6dpgy4DFKIhRbcp9SStEFTPaCROQrDPwXYmqtDlXDY/8vdwjY6AqycZkayBRYy13UbHO+tLtA+6FTRQ/mjoNMaqlX73L8TVVI=,iv:FH8f/pCz0m+d0EUbX0yRJubiZxe7/V9lyfaHfDj0Cxc=,tag:I4StrJzYspOQAH89zWJevw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
