apiVersion: v1
kind: ConfigMap
metadata:
    name: qbtools-config
data:
    config.yaml: ENC[AES256_GCM,data:n9sS9YbBWdwHMNHqsjvD+fACpXxslcnSnfGtkwfnPf/cPsCv4m2Uj8AIhN0NIpP0gI0SOq+cmpRukfN71Bq8CzBCCIrk9LRl8D+ZyNvPPx5BfMNet4uAY2Q13qGxD5agLQrIMTNk0MDDTgSLu6iDOYHFny/3HuBU41jRWrJZk633h40wM3I0Asmh+8BXoy5WeU0dauQIVXOlFg+8RpACL1IQE4FOP9NQevinlJZ3ZcfyF4GppRJQzZB6ZOrVfsCj3ipP3qwTjwglGDdngEVKVUHf5mwXYA==,iv:c0UtfBOlE2w5fUJtLnor4/MFdD8u1kuVaaNfKAKVdng=,tag:Es/6+9NKqZzylYryh1kvZg==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WWZkOUhMd3N1M3FJTzZG
            bGprZ2F2N2cwV1lzdTBkOEdHejF1VUpiVVY0Cmk2cnB5bEZhaERjMS9mZlBiQkxu
            RFUwQnI1NVNoWkQ4Z2JJY0hwS2lYOGMKLS0tIG0yd0pxdkg2NGZ0SVhBSXdsdVdC
            a1Uya3lvQ0JnVjUxTGZJVnNmN3RISG8KzpR3zfk6dKKpkALhNXJwuKjh3Y44F0R4
            y0qxX4gmlExS6+3JOpb9lK4S28fdAbVhlqWGGesF2fZ5ZHitDJQEWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T12:00:55Z"
    mac: ENC[AES256_GCM,data:rAAMG65LTTyK9msPbLbRp71hT7iDcfoa8GFpFu25I7NH8iqeWS+ApjzRMANaUweBTCb/z9q9a/ui3Y+2birLHnqC233vtXFNBd37gJk+wJ7D1UM29pcj51F+2vlzZUkgCu0lyrJUxjnU9KTnkUSzOGFXe8Gb79KalCUws1a2qUM=,iv:qC9I621pyM4SX7DlNPc/ZeMU5buFQlEzb+usnwEwdnw=,tag:rG0MoHoOgzA9P2ij4cUxCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
