controllers:
  tagging:
    type: cronjob
    cronjob: &cronJobSpec
      schedule: 0 * * * *
      backoffLimit: 0
      concurrencyPolicy: Forbid
      successfulJobsHistory: 1
      failedJobsHistory: 1
      ttlSecondsAfterFinished: 3600
    initContainers:
      tag: &container
        image:
          repository: ghcr.io/buroa/qbtools
          tag: v0.21.1@sha256:fd13085f7534719b7b30828684661b7f5611bbc4156831123775cfcd9b8f2eb5
        env:
          QBITTORRENT_HOST: qbittorrent.media.svc.cluster.local
          QBITTORRENT_PORT: 8080
        args:
          [
            "tagging",
            "--added-on",
            "--expired",
            "--last-activity",
            "--sites",
            "--unregistered",
            "--not-linked",
          ]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 25m
          limits:
            memory: 128Mi
    containers:
      unregistered:
        <<: *container
        args: [
            "prune",
            "--exclude-category",
            "manual",
            "--exclude-category",
            "music",
            "--exclude-tag",
            "added:1d",
            "--include-tag",
            "unregistered",
            "--with-data",
            #"--dry-run",
          ]
      # remove cross-seeds after one day
      cross-seed:
        <<: *container
        args: [
            "prune",
            "--exclude-category",
            "manual",
            "--exclude-tag",
            "added:1d",
            "--include-tag",
            "cross-seed",
            "--with-data",
            #"--dry-run",
          ]
      # remove unlinked and expired torrents after one day
      unlinked:
        <<: *container
        args: [
            "prune",
            "--exclude-category",
            "manual",
            "--exclude-tag",
            "added:1d",
            "--include-tag",
            "expired",
            "--include-tag",
            "not-linked",
            "--with-data",
            #"--dry-run",
          ]
    pod:
      restartPolicy: Never
  orphaned:
    type: cronjob
    cronjob:
      <<: *cronJobSpec
      schedule: 0 0 * * 0
      suspend: true
    containers:
      app:
        <<: *container
        args: ["orphaned", "--exclude-pattern", "*_unpackerred*"] #", --dry-run"]
    pod:
      restartPolicy: Never
  reannounce:
    containers:
      app:
        <<: *container
        args: ["reannounce", "--process-seeding"]

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
persistence:
  secret-file:
    type: configMap
    name: qbtools-config
    globalMounts:
      - path: /config/config.yaml
        subPath: config.yaml
        readOnly: true
  media:
    existingClaim: media
    globalMounts:
      - path: /media/Downloads/qbittorrent
        subPath: Downloads/qbittorrent
