apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: tqm-secret-generator
secretFrom:
  - metadata:
      name: tqm-secret
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    type: Opaque
    files:
      - config.yaml=./resources/config.enc.yaml
