apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: "xfs"
  recurringJobSelector: '[
    {
    "name":"backup-group",
    "isGroup":true
    }]'
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
