defaultSettings:
  defaultDataPath: /var/mnt/extra/longhorn
  defaultLonghornStaticStorageClass: longhorn
  storageReservedPercentageForDefaultDisk: 10
  replicaSoftAntiAffinity: true
  replicaDiskSoftAntiAffinity: false
  replicaAutoBalance: least-effort
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain
