apiVersion: v1
kind: Secret
metadata:
    name: autobrr-secret
data:
    AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:WVfZqnntugD8Pbz7aHYvHoLFq4SDCHV5i3qkrsCFW2EKqDj+APrNne9n4RxdVDHQyNwrBsJLE0g=,iv:lFGdXj8RIOuxyff0DWlblJpUKcpzE+FldFz8NajxWA8=,tag:WxC2NAMrLaXBk6aubTAIvQ==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbmxmM2tOYitrQktxcUZx
            eUwzVEZ5RWNsaWtXb3VPclExcll6L280blVzCkJxTlFXcnRubGZEbEdIbkdTSytL
            TWVVaGJCMU1zaWpTTG9VbE42WmlCRnMKLS0tIGNBamROM0ttVXdCcDZRVk1aUDBU
            UHFVdGhCcENtNnhMcGxGKytPRFpRTFUKL7kQB5XsYLCxAeMPkXO5beGu31fnKj5f
            HreryEX2bu3c2Sx2mmi7QKQ+rDBJz71pRjtyfExvL9M1+JUJa652Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-09T13:40:27Z"
    mac: ENC[AES256_GCM,data:7iDUEyugLNSt4kNuwuGpUmBPN5ziIH9tlXeU4qcV1/yVXrUvFWv+1nv2Be3TdW50Q9hqG8YTJjK93zdedDtEccmksb3D2rfRqA7Xs+VO/hK65WVhbkCD3tuvJBKC7ArC6hhZwI1wiSEGF3iSWNU8eJ9U1LGl5ZGJLHBwVgZ8heE=,iv:ibaDYRpurZ47vuny+vj4wR03NZajDn0vMeDeXqwU5N0=,tag:Kospzr8fDXdfJy22lBr/1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
