genconfig:
  talosctl gen config --force --with-secrets secrets.yaml --config-patch-control-plane @nodepatch.yaml homecluster https://192.168.1.123:6443

applyconfig:
  talosctl apply-config -n 192.168.1.123 --file controlplane.yaml --insecure

apply:
  talosctl apply-config -n 192.168.1.123 -e 192.168.1.123 --file controlplane.yaml --talosconfig=./talosconfig

gensecrets:
  talosctl gen secrets -o secrets.yaml

bootstrap:
  talosctl bootstrap --nodes 192.168.1.123 --endpoints 192.168.1.123 --talosconfig=./talosconfig

debug:
  kubectl debug -n kube-system -it --image ubuntu node/homecluster --profile=sysadmin

dashboard:
  talosctl -n 192.168.1.123 -e 192.168.1.123 --talosconfig=./talosconfig dashboard

do +AARGS:
  talosctl -n 192.168.1.123 -e 192.168.1.123 --talosconfig=./talosconfig {{ AARGS }}