---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - ./resources/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
