apiVersion: v1
kind: Secret
metadata:
    name: bookboss-secret
stringData:
    BOOKBOSS_ENCRYPTION_SECRET: ENC[AES256_GCM,data:IRsefxOxI0XdFiIURi2hBnyxAGIhjGA+shrhoADvRl1eJMQs9Yr/aRZYB7g=,iv:OIPF6Z9RFsecr62HoQndHegt/S658ILO16BRnMRUeTs=,tag:6K3pcG0HGL9XHExjesnKYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM1I4UWJVVzhtMDlLQ09H
            UHJCVWxPVTVSUlQ2c3ZyTDZyZVppZTI2bUJ3CnhQU29UbXk4ZlhoZDFURnIvdXJ0
            aCtkeE9Xd2svTnE5MGNXeHBvRy9lZmMKLS0tIGJvbWdmMXNGdi9BL3FBRzVGWlN6
            QUdITnMrNWRFQ0VVWko4Y2UxdlIzUGcKVOMqv/xlCF/ZDSGFfvxtGjOJNpd0axv4
            nT9t4glMdEdQDEFsCap/+7q9OtZt5lQMr5Xso15aQpXqevzQzaPk1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T17:41:23Z"
    mac: ENC[AES256_GCM,data:jV0pBHmlJJgCTmx5R83Pf5oe/afoFAv9eUfgeJjO3jX9Z/ASaC2IrXNjHPk2EswjvrSAUy6cxcNRmsYC708LpviqeneQvxFKG59xBYSjh32IlcT4CRD7kYGZZPK9uWT1yLNVCbJp8tw5kq0j9Ji/7hVvvyiESNF9iRL3kDyQpOM=,iv:YBz50spLBSLZcdUFKOf28Q9TsI57OX5C61lVUiObfBY=,tag:Is6Dp6g2UlWBGrdfQdDjhQ==,type:str]
    version: 3.13.1
