apiVersion: v1
kind: Secret
metadata:
    name: bookboss-secret
stringData:
    BOOKBOSS__ENCRYPTION_SECRET: ENC[AES256_GCM,data:zQGSa3k2PrIkpZC3h+F+erzMdODwJJE8c9MhO+PP6hpdatNJlYwyeoOCphY=,iv:ymCbYaVWQiw4QTIhGHTf+R4oMxFo/Lyoxj37DOnnndQ=,tag:K6PHcYo5Q4DnEdIeMhFAmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5LzU5Nks5cTlUbHZRU3pP
            dzNVUWVsUUYwL2RNcFgwTWI5c0Jad1FYTnhFCmYvcktxdXUxVVBBTG15cmMyMkZS
            Zkhnei93K09FdjkvVUlrbmJsWEZBZ00KLS0tIEdzaVVha1NwOE9XQWtkMG5lTFFF
            QlBtcUp1eDdZNHhzVWJ5Mzh6Skx0OWcK4uaY/zyctspoKNpdXfIi7w63ytWwLyS5
            L/rMs48iDEE7RkgtzCNMhze+JUhTkS0n1QZeQm1GX5h+iBovPIw/Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T08:18:46Z"
    mac: ENC[AES256_GCM,data:hbMXIxxAeiHnx1SDK7gXCnCPcsj9pxdfYymtgBhnQRMfGQbvy95VXCrleV37SLijD1kT2trv9LQ0X2hHjZc/86TmO2Uz8U1+5ik7bjZ0SqrXqFMK/zk2FwvQqLpyyCyGx+7KRHYSzWSVUJxyWHQjbrU/rmbZfqvZZIHDsR2hyBA=,iv:g1a862yzIH0hAwtfO8tIiLrzgxMWgKUUseFsKeookus=,tag:a+SHKPE/LEQ+ex/ORWUJ5w==,type:str]
    version: 3.13.1
