apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          webhook:
            groupName: lego.dns-solver
            solverName: lego-solver
            config:
              # available provider refer to https://go-acme.github.io/lego/dns/#dns-providers
              provider: desec
              envFrom:
                secret:
                  name: desec-api-token
          cnameStrategy: Follow
        selector:
          dnsZones:
            - devpi.de
