apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.1
    releaseName: cert-manager
    valuesFile: ./values.yaml
generators:
  - ./secret-generator.yaml
resources:
  - ./issuer-letsencrypt-staging.yaml
