apiVersion: v1
kind: Secret
metadata:
    name: dynv6-api-token
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:S/6ICzNKr+ZifGbDXSEZPpa/HKfmINApFLWzcaCcamQm/Q2gVkDR+f/q0+zOftYPMnICfDXfJ/jAAvmoXwNvqJ9lgUNzb70MP3HxvymQCjdOqUghzOrFXjbN1r/DqFN/WmyKD2iyx18Q8eqyRP55P7kFeNLP+g8+,iv:KN57HvcEYdglQHPC0iJxrvWDA1zfxLIBXlFWWWJMInA=,tag:M6FOEDetdS6lwOQqU1qBRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMmdEQnNtckVkdnNsc0ZE
            S2cxYjhYUStqdjVyQlRZS1RkYWtuUi9uWlhVCk43S0Exb1o5OEU3MjlKRmNYSVdE
            VUZNdjNtVkF1cHBHMTRsSFppV3A0ZXcKLS0tIEpmcUcrS3pnYkEwenROVUppTzZT
            TkFXVnQ4VHNkRFE0QWdvTDRXWmtOeUEKQ9Xv5t9EvMpNg/nspOCWYB7aWpqF8cRk
            kSiKTsm6B/sOJfSSxn8S/o+kPWWTpyOQ2UHk87Anph4UgQESlPJZdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T16:39:36Z"
    mac: ENC[AES256_GCM,data:W9tWMJ+NyAMUNSj7LBakKPQEcZCTRDwb9EpNemdUfhvPxaOHfHm5yAYuRvi4y1nXNOKIlwmCF8RriRDV7YznDg2JrRPQX+L7NmHEfvS3MJ4LK5vwI91LWyw/VlNl1DoGI+WtPeWEGdImkzjQUeEM3wLjDYhu5r8yvxCD2w/FA+8=,iv:zCbRbSxslz8tuGSuBk4U6Kahl6dyZ5NIjTmcVb+Pdw0=,tag:4jsRPrPCd8aUsEH/ah24mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
