apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-everywhere
spec:
  selectors:
    - podSelector:
        matchLabels: {}
  destinationCIDRs:
    - "2000::/3"

  egressGateway:
    nodeSelector:
      matchLabels: {}

    interface: "bond0"
