apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pool.yaml
  - ./gatewayconfig.yaml
  - ./gateway-http.yaml
  - ./netbird-routing-peer.yaml
generators:
  - ./secret-generator.yaml