apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
data:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:Z4Bg1NUNssQTmPE7xGgJBua6+R5Tb5oVcoJ6mGHIO4X9jXaPYXIb+TDuijlF+h9kM8eTIdrgFCM=,iv:oLyrpiXiAIoY83JuEF1cclkrzRulplAdYQhcYDAlofo=,tag:OyH9iZ/DmeTejUYhaTsTwA==,type:str]
sops:
    age:
        - recipient: age1zc4knw29dcgns9zdpyxyx56xsax6s9vsu82sgef3mph56mdr7fusp6v9yh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNUpoRXJPbk1GbWZxcU9R
            UStQQWw1VWtFbDdLeGQ4RnMzWTRDMFp3NkdnCkx1REp3b29uYXZxS0swazdlTnlr
            SnF2ODh1NVEraVVtdkFINHJXT3ZuQlkKLS0tIGZvR3oxSlN2T1Y4eStpK0RaZ0Na
            cHlqaXVQRE1VNytXKytCbHIyZVZyQTQKSH3ZrQZq8Aahrxp/kTgSHl4D+SAFNr5O
            Z1FjgUiLW5oISYH0OkgLyFaITDA53mSDuNvBmm3BjhCeGCqQSocNkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T18:09:54Z"
    mac: ENC[AES256_GCM,data:AjkEUNIwGaPhwOdCII8Bqz+BtlpJ0SQ9RDweUDS/UlfbiJVHxRQsz+779cUrdGo6AjXUrkhQLzlDKEqE6BjP0JFViOvPQST7bMSU1HrnOQ6b9zE75A8vhokB4M2XMZYhSrGU7iSQV2yreC+ouE28MBTckPgPPvMr/LcfrDiUP7w=,iv:egeDMm4tbicjyjjU/i9ex7cw0IYDN97XupM3/7pm9EQ=,tag:VGYlwmzf5XVqQYZFYJc7qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
