---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pool.yaml
patches:
  - target:
      kind: Service
      name: cilium-ingress
    patch: |-
      - op: replace
        path: /spec/ipFamilies
        value:
          - IPv4
          - IPv6
      - op: replace
        path: /spec/ipFamilyPolicy
        value:
          PreferDualStack