
ipv4:
  enabled: true

ipv6:
  enabled: true

ipv6NativeRoutingCIDR: "fd7f:eaef:3171::/96"
ipv4NativeRoutingCIDR: "10.244.0.0/16"
autoDirectNodeRoutes: true
routingMode: native

bpf:
  masquerade: true

devices: bond+

hubble:
  enabled: false

kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

ipam:
  mode: kubernetes

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false

  hostRoot: /sys/fs/cgroup

k8sServiceHost: localhost
k8sServicePort: 7445

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

operator:
  replicas: 1

ingressController:
  enabled: true
  loadbalancerMode: shared
  service.allocateLoadBalancerNodePorts: false